### ISSUE TITLE
Tutorial fails to run 

### ISSUE THREAD

**Issue by Pysassin** [mellinoe/veldrid#148]
I am attempting to run the Getting Started Tutorial and have strait copy pasted the code thinking I screwed something up. When attempting to run I get a fatal crash. Get the following exception:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Veldrid
  StackTrace:
   at Veldrid.D3D11.D3D11Shader.CompileCode(ShaderDescription description) in C:\projects\veldrid\src\Veldrid\D3D11\D3D11Shader.cs:line 83
   at Veldrid.D3D11.D3D11Shader..ctor(Device device, ShaderDescription description) in C:\projects\veldrid\src\Veldrid\D3D11\D3D11Shader.cs:line 27
   at Veldrid.D3D11.D3D11ResourceFactory.CreateShaderCore(ShaderDescription& description) in C:\projects\veldrid\src\Veldrid\D3D11\D3D11ResourceFactory.cs:line 60
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription description) in C:\projects\veldrid\src\Veldrid\ResourceFactory.cs:line 393
   at GettingStarted.Program.LoadShader(ShaderStages stage) in C:\Codebases\VeldridTest2\VeldridTest2\Program.cs:line 127
   at GettingStarted.Program.CreateResources() in C:\Codebases\VeldridTest2\VeldridTest2\Program.cs:line 76
   at GettingStarted.Program.Main(String[] args) in C:\Codebases\VeldridTest2\VeldridTest2\Program.cs:line 33

**Comment by Pysassin** [comment]
Changing the LoadShader switch to use .hlsl instead of .hsls.bytes corrects the issue.

**Comment by mellinoe** [comment]
I'm re-working most of the shaders in the samples to use Veldrid.Spirv, which will indirectly fix this problem.

**Comment by mellinoe** [comment]
The [spirv branch](https://github.com/mellinoe/veldrid-samples/tree/spirv) is available now, which should fix this. I still need to test on a few extra platforms before merging it in to master.

**Comment by mellinoe** [comment]
I've merged all of the changes into the master branch over there, so there shouldn't be any problems like this now.

**Comment by chances** [comment]
I'm receiving this error compiling using both SPIR-V with Veldrid.Spirv or direct HLSL in Veldrid 4.6.1
