### ISSUE TITLE
Cannot load libassimp.dylib when running AnimatedMesh sample on mac

### ISSUE THREAD

**Issue by tzachshabtay** [mellinoe/veldrid#159]
Sounds similar to #52 but happens on a mac (fresh clone from today).

```
Unhandled Exception: System.IO.FileNotFoundException: Could not find or load the native library: libassimp.dylib
   at NativeLibraryLoader.LibraryLoader.LoadNativeLibrary(String name, PathResolver pathResolver)
   at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
   at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
   at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
   at Assimp.AssimpContext.CreateConfigs()
   at Assimp.AssimpContext.ImportFileFromStream(Stream stream, PostProcessSteps postProcessFlags, String formatHint)
   at AnimatedMesh.AnimatedMesh.CreateResources(ResourceFactory factory) in /Users/zachi/Projects/veldrid-samples2/veldrid-samples/src/AnimatedMesh/Application/AnimatedMesh.cs:line 107
   at SampleBase.SampleApplication.OnGraphicsDeviceCreated(GraphicsDevice gd, ResourceFactory factory, Swapchain sc) in /Users/zachi/Projects/veldrid-samples2/veldrid-samples/src/SampleBase/SampleApplication.cs:line 39
   at SampleBase.VeldridStartupWindow.Run() in /Users/zachi/Projects/veldrid-samples2/veldrid-samples/src/SampleBase/VeldridStartupWindow.cs:line 60
   at AnimatedMesh.Program.Main(String[] args) in /Users/zachi/Projects/veldrid-samples2/veldrid-samples/src/AnimatedMesh/Desktop/Program.cs:line 11
```

macOS version 10.14 (Moave)

**Comment by mellinoe** [comment]
@tzachshabtay Thanks for catching this. It turns out that the AnimatedMesh project file was referencing a different version of the AssimpNet package, which didn't include the OSX binary in it. I've corrected this, so you should be able to run this sample on the master branch now.

**Comment by tzachshabtay** [comment]
@mellinoe thanks, note though that I used AnimatedMesh as an example, but I think there were other projects that had the same error.
