### ISSUE TITLE
Trouble running NeoDemo sample on macOS, tries to load libvulkan.dylib

### ISSUE THREAD

**Issue by christianscheuer** [mellinoe/veldrid#167]
I'm getting the following error when trying to run the NeoDemo sample on macOS 10.12.6.
As far as I understand Vulkan is not available for Mac? Is it possible that somehow during build it picks the wrong backend?

Any ideas on what I might do to help make it work?

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Vulkan.VulkanNative' threw an exception. ---> System.InvalidOperationException: Could not load libvulkan.dylib
   at Vulkan.NativeLibrary..ctor(String libraryName)
   at Vulkan.NativeLibrary.Load(String libraryName)
   at Vulkan.VulkanNative..cctor()
   --- End of inner exception stack trace ---
   at Vulkan.VulkanNative.vkEnumerateInstanceLayerProperties(UInt32& pPropertyCount, VkLayerProperties* pProperties)
   at Veldrid.Vk.VulkanUtil.EnumerateInstanceLayers() in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid/Vk/VulkanUtil.cs:line 84
   at Veldrid.Vk.VkGraphicsDevice.CreateInstance(Boolean debug, VulkanDeviceOptions options) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid/Vk/VkGraphicsDevice.cs:line 426
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid/Vk/VkGraphicsDevice.cs:line 106
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid/Vk/VkGraphicsDevice.cs:line 102
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid/GraphicsDevice.cs:line 974
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid.StartupUtilities/VeldridStartup.cs:line 222
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid.StartupUtilities/VeldridStartup.cs:line 209
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid.StartupUtilities/VeldridStartup.cs:line 112
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd) in /Volumes/Intern_HDD1/d2/veldrid/src/Veldrid.StartupUtilities/VeldridStartup.cs:line 44
   at Veldrid.NeoDemo.NeoDemo..ctor() in /Volumes/Intern_HDD1/d2/veldrid/src/NeoDemo/NeoDemo.cs:line 60
   at Veldrid.NeoDemo.Program.Main(String[] args) in /Volumes/Intern_HDD1/d2/veldrid/src/NeoDemo/Program.cs:line 9
```

**Comment by mellinoe** [comment]
Sorry about that -- the latest version in master should use Metal by default now, if you are on macOS. NeoDemo isn't very good about doing platform checks up front, and occasionally I change the default while testing things.

By the way, you can use the Vulkan backend on macOS if you install the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home).
