### ISSUE TITLE
OpenGL backend on OSX Mojave always throws and error on closing the window context

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#197]
I dont know if its related to the clamping issue. But I switched to master instead of 4.6.1 and now if I close any project with an OpenGL backend I get the following error.

`An exception of type 'Veldrid.VeldridException' occurred in Veldrid.dll but was not handled in user code: 'glGetError indicated an error: InvalidFramebufferOperationExt'
   at Veldrid.OpenGL.OpenGLUtil.CheckLastError() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLUtil.cs:line 24
   at Veldrid.OpenGL.OpenGLCommandExecutor.ClearColorTarget(UInt32 index, RgbaFloat clearColor) in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLCommandExecutor.cs:line 68
   at Veldrid.OpenGL.NoAllocEntryList.OpenGLNoAllocCommandEntryList.ExecuteAll(OpenGLCommandExecutor executor) in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/NoAllocEntryList/OpenGLNoAllocCommandEntryList.cs:line 228
   at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.ExecuteWorkItem(ExecutionThreadWorkItem workItem) in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs:line 1131
   at Veldrid.OpenGL.OpenGLGraphicsDevice.ExecutionThread.Run() in /Users/marchaubenstock/Workspace/DotNet/veldrid/src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs:line 1116
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)`

Metal works fine. And as mentioned OpenGL works fine on NuGet v 4.6.1
Im running OS Mojave 10.14.5

**Comment by geoeo** [comment]
From what I can tell the `WorkItemType.TerminateAction`case in OpenGLGraphicsDevice does not trigger.  Instead Veldrid still tries to to an ExecuteList after I closed the context window. But then again I dont really know what the status-quo of this is supposed to be.

**Comment by geoeo** [comment]
Somehow something changed in the SDL window handling. 
Before my render loop was as follows:

     while(contextWindow.Exists){
        InputSnapshot inputSnapshot = _contextWindow.PumpEvents();
        render
        ...
      }

However now I have to check again after `PumpEvents()`

    while(contextWindow.Exists){
        InputSnapshot inputSnapshot = _contextWindow.PumpEvents();
         if(!contextWindow.Exists)
               break;
        render
        ...
      }
