### ISSUE TITLE
Error compile shader dx11 backend 

### ISSUE THREAD

**Issue by IBets** [mellinoe/veldrid#199]
I tested my application on four computers. Two of them do not support VulkanAPI so I chose the DX11 backend. The first one does not have a GPU, but if you select a DX11 backend, it is emulated and everything works fine. The second computer gives this error even though it has a discrete GPU

> Unhandled Exception: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.
> 
> at SharpDX.Result.CheckError()
> at SharpDX.Direct3D11.Device.CreateVertexShader(IntPtr shaderBytecodeRef, PointerSize bytecodeLength, ClassLinkage classLinkageRef, VertexShader vertexShaderOut)
> at SharpDX.Direct3D11.VertexShader..ctor(Device device, Byte[] shaderBytecode, ClassLinkage linkage)
> at Veldrid.D3D11.D3D11Shader..ctor(Device device, ShaderDescription description) in C:\projects\veldrid\src\Veldrid\D3D11\D3D11Shader.cs:line 33
> at Veldrid.D3D11.D3D11ResourceFactory.CreateShaderCore(ShaderDescription& description) in C:\projects\veldrid\src\Veldrid\D3D11\D3D11ResourceFactory.cs:line 60
> at Veldrid.SPIRV.ResourceFactoryExtensions.CreateFromSpirv(ResourceFactory factory, ShaderDescription vertexShaderDescription, ShaderDescription fragmentShaderDescription, CrossCompileOptions options)
> at Veldrid.SPIRV.ResourceFactoryExtensions.CreateFromSpirv(ResourceFactory factory, ShaderDescription vertexShaderDescription, ShaderDescription fragmentShaderDescription)

**Comment by mellinoe** [comment]
Hm, that's a strange error to receive after you've gotten that far. Can you provide a repro (including a sample shader) that exhibits this problem? Are you able to run NeoDemo on this machine?

**Comment by IBets** [comment]
NeoDemo does not work on this machine.

**Comment by dajuric** [comment]
Hi. I have the same issue. I have tried running the NeoDemo, but it throws the same error.
Do you know what should I do ?

Screenshot:
[Screenshot of the error]([url=https://ibb.co/9ZKtjvn][img]https://i.ibb.co/RjryWS2/error.png[/img][/url])

**Comment by dajuric** [comment]
It appears that this error is caused by a GPU driver. After re-installation, it works.

**Comment by mellinoe** [comment]
@dajuric Could you give a bit more info about which drivers you were using that caused an issue, and which ones do not?

**Comment by dajuric** [comment]
Hi Eric,

    it seems that GPU drivers were not functioning properly.
    I have Intel HD3000 and NVidia GeForce 520MX.
    I reinstalled NVidia drivers - the error still remained, although I
forced execution on that card.
    Finally, I had uninstalled Intel's drivers and re-installed them. That
fixed the issue.

    let me know, if more info is needed.

Best,
Darko


pon, 1. srp 2019. u 05:58 Eric Mellino <notifications@github.com> napisao
je:
