### ISSUE TITLE
Access violation error with 1.0.12

### ISSUE THREAD

**Issue by philstopford** [mellinoe/veldrid#224]
With reference to this project : 

github.com/philstopford/Eto.Veldrid

updating the spirv from 1.0.9 to 1.0.12 yields an access violation : 

for Direct3D11 or OpenGL backends.

Build/run the WPF project and things should explode with 1.0.12 (1.0.9 is configured in the project and should work fine). The shaders are in the project.

{{{
System.OverflowException
  HResult=0x80131516
  Message=Array dimensions exceeded supported range.
  Source=Veldrid.SPIRV
  StackTrace:
   at Veldrid.SPIRV.SpirvCompilation.CompileVertexFragment(Byte[] vsBytes, Byte[] fsBytes, CrossCompileTarget target, CrossCompileOptions options)
   at Veldrid.SPIRV.ResourceFactoryExtensions.CreateFromSpirv(ResourceFactory factory, ShaderDescription vertexShaderDescription, ShaderDescription fragmentShaderDescription, CrossCompileOptions options)
   at VeldridEto.VeldridDriver.CreateResources() in D:\development\git\Eto.Veldrid\src\Eto.VeldridSurface\VeldridDriver.cs:line 1117
   at VeldridEto.VeldridDriver.SetUpVeldrid() in D:\development\git\Eto.Veldrid\src\Eto.VeldridSurface\VeldridDriver.cs:line 1026
   at VeldridEto.MainForm.SetUpVeldrid() in D:\development\git\Eto.Veldrid\src\Eto.VeldridSurface\MainForm.cs:line 170
   at VeldridEto.MainForm.set_FormReady(Boolean value) in D:\development\git\Eto.Veldrid\src\Eto.VeldridSurface\MainForm.cs:line 37
   at VeldridEto.MainForm.<.ctor>b__12_0(Object sender, EventArgs e) in D:\development\git\Eto.Veldrid\src\Eto.VeldridSurface\MainForm.cs:line 48
   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
   at Eto.Forms.Control.OnShown(EventArgs e)
   at Eto.Forms.Control.Callback.OnShown(Control widget, EventArgs e)
   at Eto.Wpf.Forms.WpfWindow`3.<AttachEvent>b__29_7()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at VeldridEto.MainClass.Main(String[] args) in D:\development\git\Eto.Veldrid\src\gui\Eto.Veldrid.Wpf\Program.cs:line 124
}}}

**Comment by mellinoe** [comment]
Hey @philstopford , did you resolve this on your end, or should I still investigate?

**Comment by philstopford** [comment]
Combination of user error in build config (special sauce) and a change in 1.0.12 that some clarification would help with  : 

Rob (the upstream developer of the Eto Veldrid project) had issues with OpenGL rendering blank until he changed references to "ViewMatrix" to "vdspv_0_0", and then changed "ModelMatrix" to ""vdspv_1_0"

Is that expected/required?

**Comment by mellinoe** [comment]
Yes, that is an accidental but expected breaking change in the 1.0.12 version right now. I am hoping to fix that soon so that the new behavior is opt-in instead of automatic. Getting an access violation before compilation even finishes sounded very different. Until the fix is in, updating the references in code will work.

**Comment by philstopford** [comment]
The access violation was due to some variable usage to define the spirv version, and it seemed to be falling back to 1.0.0 because I missed the special sauce needed. That resulted in the access violation. This coincided with the 1.0.12 breaking change, I think, so two causes for one common point of failure.
