### ISSUE TITLE
Vk IndependentBlend seems to be detected but not enabled for custom blend states

### ISSUE THREAD

**Issue by JulienNoble** [mellinoe/veldrid#235]
I'm trying to create a pipeline with multiple color targets on a Vulkan backend, Windows 10 (for a Weighted, Blended OIT implementation), but I'm getting a weird validation error about independent blend not being enabled, hence not allowing different blend attachments.

But I checked my code and `VkGraphicsDevice`, I do have the `IndependentBlend` in my features detected from device and set to true when running (running an nv 2080RTX, I'd wager it does support such features). I might be setting something wrong? Here's my pipeline creation code :

```csharp
this.pipeline = ResourceFactory.CreateGraphicsPipeline (
    new GraphicsPipelineDescription (
        new BlendStateDescription
        {
            AttachmentStates = new BlendAttachmentDescription[]
            {
                // accum
                new BlendAttachmentDescription
                {
                    BlendEnabled = true,
                        AlphaFunction = BlendFunction.Add,
                        ColorFunction = BlendFunction.Add,
                        SourceAlphaFactor = BlendFactor.One,
                        SourceColorFactor = BlendFactor.One,
                        DestinationAlphaFactor = BlendFactor.One,
                        DestinationColorFactor = BlendFactor.One,
                },
                // revealage
                new BlendAttachmentDescription
                {
                    BlendEnabled = true,
                        AlphaFunction = BlendFunction.Add,
                        ColorFunction = BlendFunction.Add,
                        SourceAlphaFactor = BlendFactor.Zero,
                        SourceColorFactor = BlendFactor.Zero,
                        DestinationAlphaFactor = BlendFactor.InverseSourceAlpha,
                        DestinationColorFactor = BlendFactor.InverseSourceColor,
                }
            }
        },
        new DepthStencilStateDescription (
            depthTestEnabled: true,
            depthWriteEnabled: false,
            comparisonKind: ComparisonKind.LessEqual),
        // ... more pipeline settings
    }
);
```

This is the actual stacktrace when running it

```
Exception has occurred: CLR/Veldrid.VeldridException
An unhandled exception of type 'Veldrid.VeldridException' occurred in Veldrid.dll: 'A Vulkan validation error was encountered: [ErrorEXT] (DeviceEXT)  [ VUID-VkPipelineColorBlendStateCreateInfo-pAttachments-00605 ] Object: 0x162ac984a40 (Type = 3) | Invalid Pipeline CreateInfo: If independent blend feature not enabled, all elements of pAttachments must be identical. The Vulkan spec states: If the independent blending feature is not enabled, all elements of pAttachments must be identical (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPipelineColorBlendStateCreateInfo-pAttachments-00605)'
   at Veldrid.Vk.VkGraphicsDevice.DebugCallback(UInt32 flags, VkDebugReportObjectTypeEXT objectType, UInt64 object, UIntPtr location, Int32 messageCode, Byte* pLayerPrefix, Byte* pMessage, Void* pUserData)
   at Vulkan.VulkanNative.vkCreateGraphicsPipelines(VkDevice device, VkPipelineCache pipelineCache, UInt32 createInfoCount, VkGraphicsPipelineCreateInfo& pCreateInfos, VkAllocationCallbacks* pAllocator, VkPipeline& pPipelines)
   at Veldrid.Vk.VkPipeline..ctor(VkGraphicsDevice gd, GraphicsPipelineDescription& description)
   at Veldrid.Vk.VkResourceFactory.CreateGraphicsPipelineCore(GraphicsPipelineDescription& description)
   at Veldrid.ResourceFactory.CreateGraphicsPipeline(GraphicsPipelineDescription& description)
   at Veldrid.Utilities.DisposeCollectorResourceFactory.CreateGraphicsPipelineCore(GraphicsPipelineDescription& description)
   at Veldrid.ResourceFactory.CreateGraphicsPipeline(GraphicsPipelineDescription& description)
   at Veldrid.ResourceFactory.CreateGraphicsPipeline(GraphicsPipelineDescription description)
```

A quick step into ResourceFactory.Features returns (running on vscode)

```
{Veldrid.GraphicsDeviceFeatures}
BufferRangeBinding [bool]:true
CommandListDebugMarkers [bool]:false
ComputeShader [bool]:true
DepthClipDisable [bool]:true
DrawBaseInstance [bool]:true
DrawBaseVertex [bool]:true
DrawIndirect [bool]:true
DrawIndirectBaseInstance [bool]:true
FillModeWireframe [bool]:true
GeometryShader [bool]:true
IndependentBlend [bool]:true
MultipleViewports [bool]:true
SamplerAnisotropy [bool]:true
SamplerLodBias [bool]:true
StructuredBuffer [bool]:true
SubsetTextureView [bool]:true
TessellationShaders [bool]:true
Texture1D [bool]:true
```

**Comment by JulienNoble** [comment]
found something : https://github.com/mellinoe/veldrid/blob/4abf21dfe2fca2f4ac90e68868fb89624d789987/src/Veldrid/Vk/VkGraphicsDevice.cs#L654

this feature descriptor for logical device creation currently ignores the `independentBlend` flag on the physical device features struct. Adding a simple `deviceFeatures.independentBlend = _physicalDeviceFeatures.independentBlend;` does the trick (my code has other problems, but they're unrelated to this one).

@mellinoe should I do a PR or is there a reason that the config is not passed for this feature?

**Comment by mellinoe** [comment]
Good catch. There was no reason for this to be disabled. I've pushed a change to master that fixes this issue.
