### ISSUE TITLE
Vulkan/MoltenVK: vkCreateDevice queueFamilyIndex Vulkan validation error

### ISSUE THREAD

**Issue by chances** [mellinoe/veldrid#249]
I'm trying to get a triangle going in my engine but experiencing _"Where's my triangle?"_ on macOS, so I thought to try switching from the default Metal backend to Vulkan/MoltenVK. After installing the Vulkan SDK, I experience this exception during device creation right off the bat:

```
An unhandled exception of type 'Veldrid.VeldridException' occurred in Veldrid.dll: 'A Vulkan validation error was encountered: [ErrorEXT] (PhysicalDeviceEXT)  [ VUID-VkDeviceCreateInfo-queueFamilyIndex-00372 ] Object: 0x7fb1c1db1fe0 (Type = 2) | vkCreateDevice: pCreateInfo->pQueueCreateInfos[1].queueFamilyIndex (=3) is not unique within pCreateInfo->pQueueCreateInfos array. The Vulkan spec states: The queueFamilyIndex member of each element of pQueueCreateInfos must be unique within pQueueCreateInfos (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDeviceCreateInfo-queueFamilyIndex-00372)'
   at Veldrid.Vk.VkGraphicsDevice.DebugCallback(UInt32 flags, VkDebugReportObjectTypeEXT objectType, UInt64 object, UIntPtr location, Int32 messageCode, Byte* pLayerPrefix, Byte* pMessage, Void* pUserData)
   at Vulkan.VulkanNative.vkCreateDevice(VkPhysicalDevice physicalDevice, VkDeviceCreateInfo& pCreateInfo, VkAllocationCallbacks* pAllocator, VkDevice& pDevice)
   at Veldrid.Vk.VkGraphicsDevice.CreateLogicalDevice(VkSurfaceKHR surface, Boolean preferStandardClipY, VulkanDeviceOptions options)
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions)
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc)
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription)
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb)
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window)
```

**Comment by mellinoe** [comment]
I see this after upgrading to the latest SDK as well. However, it should be a validation-only problem. This means you should be able to run with GraphicsDeviceOptions.Debug turned off

The underlying reason for this seems to be that the old MoltenVK surface extension (VK_MVK_macos_surface) has been deprecated and replaced with an official VK_EXT_metal_surface extension. MoltenVK itself seems to have stopped supporting the former, actually, and no longer indicates that any of its queues support presenting to the surface created in NeoDemo.

I will need to update Veldrid to use the new extension when available, and ideally to continue supporting the old one if it's possible. In the meantime, you should be able to run with validation disabled.

**Comment by mellinoe** [comment]
I pushed a fix to the `vulkan-ext-metal-surface`, but it's not fully tested yet.
