### ISSUE TITLE
Using a cached value of the Swapchain.Framebuffer property crashes on DX11, but works fine on Vulkan and OpenGL

### ISSUE THREAD

**Issue by jhm-ciberman** [mellinoe/veldrid#329]
I think I discovered a bug (or something that should be documented). 
Using a cached value of the Swapchain.Framebuffer property crashes on DX11, but works fine on Vulkan and OpenGL.
Here is an example code: 

```csharp
private Framebuffer _framebuffer;

private Framebuffer _swapchain;

public MyClass() 
{
    // Create Window, GraphicDevice, etc, and then
    // The problem is here, when you cache the value of the Framebuffer and then try to use it below
    this._swapchain = gd.MainSwapchain;
    this._framebuffer = this._swapchain.Framebuffer; 
}

public void Render() 
{
     // Without caching: Works fine on all platforms
    this._commandList.SetFramebuffer(this._swapchain.Framebuffer);
    
    // With caching: Crashes in this line in DX11 (Works fine on Vulkan and OpenGL)
    this._commandList.SetFramebuffer(this._framebuffer); 

    RenderStuff(); 
}
```

Here is the crash error: 
```
Unhandled exception. System.AggregateException: One or more errors occurred. (External component has thrown an exception.)
 ---> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at SharpDX.Direct3D11.DeviceContext.ClearRenderTargetView(RenderTargetView renderTargetViewRef, RawColor4 colorRGBA)
   at Veldrid.D3D11.D3D11CommandList.ClearColorTargetCore(UInt32 index, RgbaFloat clearColor)
   at Veldrid.CommandList.ClearColorTarget(UInt32 index, RgbaFloat clearColor)
   at LifeSim.Rendering.GPURenderer3D._SetupCamera(Camera3D camera) in C:\repos\medieval-life-sharp\src\rendering\GPURenderer3D.cs:line 85
   at LifeSim.Rendering.GPURenderer3D.Render(Framebuffer framebuffer, Scene3D scene) in C:\repos\medieval-life-sharp\src\rendering\GPURenderer3D.cs:line 122
   at LifeSim.Rendering.GPURenderer.<>c__DisplayClass14_0.<Render>b__0() in C:\repos\medieval-life-sharp\src\rendering\GPURenderer.cs:line 77
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at LifeSim.Rendering.GPURenderer.Render(Scene3D scene) in C:\repos\medieval-life-sharp\src\rendering\GPURenderer.cs:line 82
   at LifeSim.App.Update(Single deltaTime) in C:\repos\medieval-life-sharp\src\App.cs:line 47
   at LifeSim.Window.RunMainLoop(Action`1 mainLoop) in C:\repos\medieval-life-sharp\src\Window.cs:line 54
   at LifeSim.App..ctor() in C:\repos\medieval-life-sharp\src\App.cs:line 25
   at LifeSim.App.Main() in C:\repos\medieval-life-sharp\src\App.cs:line 9
```

I know that this is not a major issue since it is only a matter of getting the framebuffer from the swapchain instead of saving it first, but if this is intended, I think it should be documented in the "Backend Differences" part of the Veldrid documentation. 

PS: Thanks for creating such amazing library! I love it <3

**Comment by jhm-ciberman** [comment]
Well, I think it is related to the `GraphicsDevice.ResizeMainWindow()` method.
The question is, why it fails on DX11 and works perfectly fine on Vulkan and OpenGL?
