### ISSUE TITLE
Are native 32 and 64 binaries provided in the managed library?

### ISSUE THREAD

**Issue by Shadowblitz16** [mellinoe/veldrid#381]
Are native 32 and 64 binaries provided in the managed library?
I get sdl2 errors saying its not found.

I am on AnyCpu but it should auto detect right?

```
/home/shadowblitz16/RiderProjects/VeldridLearning/Core/bin/Debug/net5.0/Core
Unhandled exception. System.TypeInitializationException: The type initializer for 'Veldrid.Sdl2.Sdl2Native' threw an exception.
 ---> System.IO.FileNotFoundException: Could not find or load the native library from any name: [ libSDL2-2.0.so, libSDL2-2.0.so.0, libSDL2-2.0.so.1 ]
   at NativeLibraryLoader.LibraryLoader.LoadNativeLibrary(String[] names, PathResolver pathResolver)
   at NativeLibraryLoader.NativeLibrary..ctor(String[] names, LibraryLoader loader, PathResolver pathResolver)
   at NativeLibraryLoader.NativeLibrary..ctor(String[] names)
   at Veldrid.Sdl2.Sdl2Native.LoadSdl2()
   at Veldrid.Sdl2.Sdl2Native..cctor()
   --- End of inner exception stack trace ---
   at Veldrid.Sdl2.Sdl2Native.SDL_CreateWindow(String title, Int32 x, Int32 y, Int32 w, Int32 h, SDL_WindowFlags flags)
   at Veldrid.Sdl2.Sdl2Window..ctor(String title, Int32 x, Int32 y, Int32 width, Int32 height, SDL_WindowFlags flags, Boolean threadedProcessing)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindow(WindowCreateInfo& windowCI)
   at Core.Program.Main(String[] args) in /home/shadowblitz16/RiderProjects/VeldridLearning/Core/Program.cs:line 22

Process finished with exit code 134.
```

**Comment by Shadowblitz16** [comment]
Seems like installing sld2 with `sudo apt-get install libsdl2-2.0-0` fixes the problem.
However can we see the native libraries packaged with nuget in the future? It makes it way easier to setup.

**Comment by mellinoe** [comment]
> However can we see the native libraries packaged with nuget in the future? It makes it way easier to setup.

For things that are pretty universally available in Linux package managers (like SDL2), I'd prefer not to ship the native binaries myself. Shipping native binaries is a huge pain, and compatibility is essentially impossible to guarantee across all of the various distros out there.

**Comment by peppy** [comment]
If you *are* looking for a nuget solution, we are doing our best to [provide this](https://www.nuget.org/packages/ppy.SDL2-CS/). It should work out of the box with veldrid.

But in line with @mellinoe's response, this is bound to cause compatibility issues with at least one subset of linux distributions and I'm not sure I can recommend doing this (we are currently dealing with [one such regression](https://github.com/ppy/SDL2-CS/issues/42) on the prerelease versions on nuget so keep that in mind).

**Comment by Shadowblitz16** [comment]
does that mean I have to include sdl2 native libraries for linux or require people to install them to use my game?

**Comment by zaafar** [comment]
@Shadowblitz16 if you package your game such that you list Sdl2 as dependency, I think, Linux package manager will automatically install it.

**Comment by Shadowblitz16** [comment]
oh cool
