### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by Tarik02** [mellinoe/veldrid#402]
Veldrid currently does not work natively in macOS on Apple Silicon devices. The first problem that occurs is missing libSDL.dylib for target architecture. This can be easily fixed with simple hack:
1. Install sdl2 using homebrew `brew install sdl2`.
2. Run application passing `DYLD_LIBRARY_PATH=/opt/homebrew/lib`.

After that there's a next problem when using Metal renderer:
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_stret' in shared library '/usr/lib/libobjc.A.dylib'.
   at Veldrid.MetalBindings.ObjectiveCRuntime.objc_msgSend_stret(Void* retPtr, IntPtr receiver, Selector selector)
   at Veldrid.MetalBindings.ObjectiveCRuntime.objc_msgSend_stret[T](IntPtr receiver, Selector selector) in Veldrid.MetalBindings.dll:token 0x60001e0+0x8
   at Veldrid.MetalBindings.NSView.get_frame() in Veldrid.MetalBindings.dll:token 0x6000191+0x0
   at Veldrid.MTL.MTLSwapchain..ctor(MTLGraphicsDevice gd, SwapchainDescription& description) in Veldrid.dll:token 0x6000794+0x4b
   at Veldrid.MTL.MTLGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 swapchainDesc) in Veldrid.dll:token 0x6000712+0x23f
   at Veldrid.GraphicsDevice.CreateMetal(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription) in Veldrid.dll:token 0x6000110+0x7
   at Veldrid.StartupUtilities.VeldridStartup.CreateMetalGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in Veldrid.StartupUtilities.dll:token 0x600000e+0x28
   at Veldrid.StartupUtilities.VeldridStartup.CreateMetalGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in Veldrid.StartupUtilities.dll:token 0x600000d+0x0
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend) in Veldrid.StartupUtilities.dll:token 0x600000b+0x35
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd) in Veldrid.StartupUtilities.dll:token 0x6000004+0x20
```
It seems like Metal bridge is not ABI compatible with ARM64 Darwin.

Trying to run with OpenGL renderer is also not successful:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libveldrid-spirv' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibveldrid-spirv, 1): image not found
   at Veldrid.SPIRV.VeldridSpirvNative.CrossCompile(CrossCompileInfo* info)
   at Veldrid.SPIRV.SpirvCompilation.CompileVertexFragment(Byte[] vsBytes, Byte[] fsBytes, CrossCompileTarget target, CrossCompileOptions options) in Veldrid.SPIRV.dll:token 0x6000032+0x1bc
```

It can't load libveldrid-spirv since it is not compiled to ARM64 architecture (or it is just absent in this case like libsdl2).

**Comment by Tarik02** [comment]
https://github.com/mellinoe/ImGui.NET-nativebuild/pull/4
https://github.com/mellinoe/ImGui.NET/pull/265

**Comment by mellinoe** [comment]
All of the native libraries should be a simple recompile, I'll try to work through those and get them shipped. As for Veldrid's ObjC layer, there's very likely some shortcuts that were taken because it only supported x86 macOS. There's at least one TODO related to this; https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.MetalBindings/ObjectiveCRuntime.cs#L244-L247, and probably some other places that made assumptions that are broken on Arm64.

**Comment by mellinoe** [comment]
That said, I don't have an ARM64 macOS device to test this on.

**Comment by Tarik02** [comment]
> All of the native libraries should be a simple recompile, I'll try to work through those and get them shipped. As for Veldrid's ObjC layer, there's very likely some shortcuts that were taken because it only supported x86 macOS. There's at least one TODO related to this; https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.MetalBindings/ObjectiveCRuntime.cs#L244-L247, and probably some other places that made assumptions that are broken on Arm64.

Actually I could get simple example working, but not with Metal. The only thing I had to patch is to replace `objc_msgSend_stret<CGRect>` with `CGRect_objc_msgSend` in `NSView.frame`. With OpenGL I got it working, but with Metal I only had pink screen.

Also, there is something wrong with textures:
```
Unhandled exception. SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=234
   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk) in SixLabors.ImageSharp.dll:token 0x600143e+0x78
   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.AllocateNewBytes(Int32 bytes, Boolean isCriticalChunk) in SixLabors.ImageSharp.dll:token 0x6001436+0xf
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata) in SixLabors.ImageSharp.dll:token 0x600130d+0x18
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream) in SixLabors.ImageSharp.dll:token 0x6001303+0x0
   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream) in SixLabors.ImageSharp.dll:token 0x60012fd+0x8
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config) in SixLabors.ImageSharp.dll:token 0x6000147+0x15
   at SixLabors.ImageSharp.Image.<>c__DisplayClass98_0`1.<Load>b__0(Stream s) in SixLabors.ImageSharp.dll:token 0x6001a33+0x0
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action) in SixLabors.ImageSharp.dll:token 0x600018b+0x41
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format) in SixLabors.ImageSharp.dll:token 0x6000189+0x20
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream) in SixLabors.ImageSharp.dll:token 0x6000188+0x0
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, String path) in SixLabors.ImageSharp.dll:token 0x6000175+0x23
   at SixLabors.ImageSharp.Image.Load[TPixel](String path) in SixLabors.ImageSharp.dll:token 0x6000173+0x0
   at Veldrid.NeoDemo.Objects.Skybox.LoadDefaultSkybox() in PATH/src/NeoDemo/Objects/Skybox.cs:line 104
   at Veldrid.NeoDemo.NeoDemo..ctor() in PATH/src/NeoDemo/NeoDemo.cs:line 82
   at Veldrid.NeoDemo.Program.Main(String[] args) in PATH/src/NeoDemo/Program.cs:line 9
```

Also, I'm going to submit a pull request that adds support for SDL2 native support.

**Comment by Tarik02** [comment]
> That said, I don't have an ARM64 macOS device to test this on.

Actually I compiled and tested this on ARM64 device. It's important to check compatibility especially with older macOS version (10.13 was the default OS on Travis CI before). If there will be some problems, it is possible to build separate libraries on old x86 macOS and arm64 version on new macOS. I'm not sure if we can merge them into one universal library, if not I'm not sure how to tell .NET to use different libraries for different architectures.

**Comment by Tarik02** [comment]
I found some strange behaviour when trying to make your veldrid-samples repository working: first (getting started) example worked flawlessly, but the second (cube) didn't work with Metal (I got black screen).
After playing out with shaders (I removed any MVP matrix calculations and left vertex shader with `output = input` without any calculations) I came to the conclusion that there are some problem around uniforms passing.
Any ideas?

**Comment by Tarik02** [comment]
Yes, seems that I was right. After hardcoding all uniforms in shader code, I got something working:
<img width="1392" alt="Знімок екрана 2021-08-18 о 12 33 50" src="https://user-images.githubusercontent.com/12175048/129875117-c941b6fe-b231-43dc-9f29-3a8b071f7f6e.png">

**Comment by Tarik02** [comment]
I used Xcode Metal debugger to gain more information. It works for me only when only first uniform is used. No matter when it set, it just has to be in 0th set be 0th binding. Trying to use separate resource set does not help either.
<img width="384" alt="Знімок екрана 2021-08-18 о 17 50 47" src="https://user-images.githubusercontent.com/12175048/129920400-2b2a2489-5432-42e0-ae55-936cde54b74e.png">
Buffer actually has expected value, shader tries to use right value:
<img width="618" alt="Знімок екрана 2021-08-18 о 17 51 08" src="https://user-images.githubusercontent.com/12175048/129920475-d4b93869-8da8-4312-91bb-d4bd86151e2a.png">
<img width="1148" alt="Знімок екрана 2021-08-18 о 17 51 31" src="https://user-images.githubusercontent.com/12175048/129920535-07e8912f-a860-4aeb-b084-675fe4a13e17.png">
Geometry gets unpredictable shape:
<img width="901" alt="Знімок екрана 2021-08-18 о 17 52 26" src="https://user-images.githubusercontent.com/12175048/129920715-a47e8f29-aa14-4597-bc1b-a477ab7d677b.png">

**Comment by Tarik02** [comment]
Something super strange is happening, in order to make it working (besides changing fragment shader to not use texture, but just set color to uv coordinate) enough to make this change in vertex shader:
```
     vec4 worldPosition = World * vec4(Position, 1);
     vec4 viewPosition = View * worldPosition;
     vec4 clipPosition = Projection * viewPosition;
-    //gl_Position = clipPosition;
+    gl_Position = View * (Projection * (World * vec4(Position, 1)));
```

While writing this I noticed one strange thing. I have this shader code:
```
void main()
{
    mat4 _Projection = mat4(
        vec4(1.0296494, 0.0, 0.0, 0.0),
        vec4(0.0, 1.8304877, 0.0, 0.0),
        vec4(0.0, 0.0, -1.0050251, -1.0),
        vec4(0.0, 0.0, -0.5025126, 0.0)
    );
    mat4 _View = mat4(
        vec4(1.0, 0.0, 0.0, 0.0),
        vec4(0.0, 1.0, 0.0, 0.0),
        vec4(0.0, 0.0, 1.0, 0.0),
        vec4(-0.0, -0.0, -2.5, 1.0)
    );
    mat4 _World = mat4(
        vec4(-0.9335928, 0.28618205, -0.21564847, 0.0),
        vec4(0.0, 0.6018058, 0.79864246, 0.0),
        vec4(0.35833564, 0.74560684, -0.56184155, 0.0),
        vec4(0.0, 0.0, 0.0, 1.0)
    );
    vec4 worldPosition = _World * vec4(Position, 1);
    vec4 viewPosition = View * worldPosition;
    vec4 clipPosition = Projection * viewPosition;
    //gl_Position = clipPosition;
    gl_Position = View * (Projection * (World * vec4(Position, 1)));
    fsin_texCoords = TexCoords;
}
```

It generates the following vertex shader:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct _47
{
    float4x4 _m0;
};

struct _65
{
    float4x4 _m0;
};

struct _73
{
    float4x4 _m0;
};

struct main0_out
{
    float2 m_104 [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    float3 m_57 [[attribute(0)]];
    float2 m_106 [[attribute(1)]];
};

vertex main0_out main0(main0_in in [[stage_in]], constant _47& _49 [[buffer(0)]], constant _65& _67 [[buffer(1)]], constant _73& _75 [[buffer(2)]])
{
    main0_out out = {};
    out.gl_Position = _67._m0 * (_75._m0 * (_49._m0 * float4(in.m_57, 1.0)));
    out.m_104 = in.m_106;
    return out;
}
```

When I do this change:
```
-    vec4 worldPosition = _World * vec4(Position, 1);
+    vec4 worldPosition = World * vec4(Position, 1);
```
Note: this variable is used in next lines of code, but actually its final result is discarded.

It generates the following vertex shader code:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct _58
{
    float4x4 _m0;
};

struct _69
{
    float4x4 _m0;
};

struct _86
{
    float4x4 _m0;
};

struct main0_out
{
    float2 m_103 [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    float3 m_50 [[attribute(0)]];
    float2 m_105 [[attribute(1)]];
};

vertex main0_out main0(main0_in in [[stage_in]], constant _58& _60 [[buffer(0)]], constant _69& _71 [[buffer(1)]], constant _86& _88 [[buffer(2)]])
{
    main0_out out = {};
    out.gl_Position = _60._m0 * (_71._m0 * (_88._m0 * float4(in.m_50, 1.0)));
    out.m_103 = in.m_105;
    return out;
}
```

The first thing I note is that it changes the order of matrix multiplication. It this SPIRV bug?

**Comment by Tarik02** [comment]
Seems to be this https://github.com/mellinoe/veldrid/issues/289

**Comment by Tarik02** [comment]
Veldrid.SPIRV version 1.0.11 does not have such a problem.

**Comment by Tarik02** [comment]
Looks like there is some problem with SixLabors.ImageSharp, it parses texture wrong way:
<img width="1392" alt="Знімок екрана 2021-08-19 о 10 25 27" src="https://user-images.githubusercontent.com/12175048/130026076-bc53ce0c-537e-49a6-8321-656f1442e727.png">
Metal debugger shows texture with all black pixels but first 3 rows. Looking at `spnza_bricks_a_diff.binary` shows a lot of zero bytes.

**Comment by Tarik02** [comment]
Got NeoDemo working on Metal by using Veldrid.SPIRV 1.0.11. There is some problem with colors:
<img width="1072" alt="Знімок екрана 2021-08-19 о 12 03 53" src="https://user-images.githubusercontent.com/12175048/130041142-2aaf9364-a11d-46ca-9061-fda6948b26a6.png">

Checking "Render with multiple threads" fixes the problem.
<img width="1072" alt="Знімок екрана 2021-08-19 о 12 05 20" src="https://user-images.githubusercontent.com/12175048/130041364-94134f2e-a3a9-4e6d-8547-2829c05d89b4.png">

**Comment by adamthole** [comment]
I'm trying to get the NeoDemo running on an M1 Mac and I'm running into an issue with the Nerdbank.GitVersioning package. 
 It is throwing the following error:

Nerdbank.GitVersioning.Inner.targets(17, 5): [MSB4018] The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.PlatformNotSupportedException: osx.10.17-arm64

Did you any of you run into this, or perhaps this is a new issue with a later version of OSX?

**Comment by adamthole** [comment]
@Tarik02 Thanks for the response!  I started with a fresh pull of the veldrid repository and upgraded to .NET 6.0 and upgraded the Nerdbank.GitVersioning.  This time it worked without issue, so I must have originally not upgraded all references to Nerdbank.

Doing that (and doing steps 1 and 2 from your original post) gets me to having this error (the same one you had originally) when I run NeoDemo:

Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_stret' in shared library '/usr/lib/libobjc.A.dylib'.
   at Veldrid.MetalBindings.ObjectiveCRuntime.objc_msgSend_stret(Void* retPtr, IntPtr receiver, Selector selector)

I get this same error when using Veldrid.SPIRV 1.0.11 and 1.0.14.  

Was there anything else I needed to do to get the NeoDemo running?

**Comment by Tarik02** [comment]
@adamthole

> The only thing I had to patch is to replace objc_msgSend_stret<CGRect> with CGRect_objc_msgSend in NSView.frame.

**Comment by adamthole** [comment]
@Tarik02 Thank you.  I saw that above but I misunderstood, thinking it was only needed for OpenGL.

I've made that update, and now I'm getting an error about not being able to find libveldrid-spirv:

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libveldrid-spirv' or one of its dependencies.

Looking around in the Nuget folder it looks like the nuget package doesn't come with an osx-arm64 version, only the osx-64.  Did you have to manually compile libveldrid-spirv, or am I missing something else?

This error is being thrown in ShaderHelper.cs, line 21:

```
shader[] shaders = factory.CreateFromSpirv(
                new ShaderDescription(ShaderStages.Vertex, vsBytes, "main", debug),
                new ShaderDescription(ShaderStages.Fragment, fsBytes, "main", debug),
                GetOptions(gd));
```

Thanks again for your help!

**Comment by Tarik02** [comment]
> Looking around in the Nuget folder it looks like the nuget package doesn't come with an osx-arm64 version, only the osx-64. Did you have to manually compile libveldrid-spirv, or am I missing something else?

year, as for all native dependencies
