### ISSUE TITLE
NativeLibraryLoader throws exception on .NET 6 Mac Monterey application

### ISSUE THREAD

**Issue by guillemcaldu-popcore** [mellinoe/veldrid#457]
When trying to build a create a window in a .NET 6 on a Mac Pro M1 wiht OS Monterey the following exception is thrown.

```
System.TypeInitializationException: The type initializer for 'Veldrid.Sdl2.Sdl2Native' threw an exception.
 ---> System.IO.FileNotFoundException: Could not find or load the native library from any name: [ libsdl2.dylib ]
   at NativeLibraryLoader.LibraryLoader.LoadNativeLibrary(String[] names, PathResolver pathResolver)
   at NativeLibraryLoader.NativeLibrary..ctor(String[] names, LibraryLoader loader, PathResolver pathResolver)
   at NativeLibraryLoader.NativeLibrary..ctor(String[] names)
   at Veldrid.Sdl2.Sdl2Native.LoadSdl2()
   at Veldrid.Sdl2.Sdl2Native..cctor()
   --- End of inner exception stack trace ---
   at Veldrid.Sdl2.Sdl2Native.SDL_SetHint(String name, String value)
   at Veldrid.Sdl2.Sdl2Window..ctor(String title, Int32 x, Int32 y, Int32 width, Int32 height, SDL_WindowFlags flags, Boolean threadedProcessing)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindow(WindowCreateInfo& windowCI)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindow(WindowCreateInfo windowCI)
```

**Comment by GabrielHalvonik** [comment]
> When trying to build a create a window in a .NET 6 on a Mac Pro M1 with OS Monterey (12.4) the following exception is thrown.
> 
> ```
> System.TypeInitializationException: The type initializer for 'Veldrid.Sdl2.Sdl2Native' threw an exception.
>  ---> System.IO.FileNotFoundException: Could not find or load the native library from any name: [ libsdl2.dylib ]
>    at NativeLibraryLoader.LibraryLoader.LoadNativeLibrary(String[] names, PathResolver pathResolver)
>    at NativeLibraryLoader.NativeLibrary..ctor(String[] names, LibraryLoader loader, PathResolver pathResolver)
>    at NativeLibraryLoader.NativeLibrary..ctor(String[] names)
>    at Veldrid.Sdl2.Sdl2Native.LoadSdl2()
>    at Veldrid.Sdl2.Sdl2Native..cctor()
>    --- End of inner exception stack trace ---
>    at Veldrid.Sdl2.Sdl2Native.SDL_SetHint(String name, String value)
>    at Veldrid.Sdl2.Sdl2Window..ctor(String title, Int32 x, Int32 y, Int32 width, Int32 height, SDL_WindowFlags flags, Boolean threadedProcessing)
>    at Veldrid.StartupUtilities.VeldridStartup.CreateWindow(WindowCreateInfo& windowCI)
>    at Veldrid.StartupUtilities.VeldridStartup.CreateWindow(WindowCreateInfo windowCI)
> ```
> 
> It's weird because the libsdl2.dylib is there, but it does not seem able to load it. Happens either with x64 or Any CPU.

Did you manage to solve this problem?

**Comment by kateusz** [comment]
working workaround:

`brew install sdl2`
then add environment variable `DYLD_LIBRARY_PATH=/opt/homebrew/lib` to `.bash_profile` or set it inside Run/Debug configuration
